### ISSUE TITLE
Better to use setuptools entry_points to install script than have separate one

### ISSUE THREAD

**Issue by jamesmyatt** [sdeancos/mqtt-client#1]
It's better to create the executable via the setuptools functionality than to store the script in `bin`

https://setuptools.readthedocs.io/en/latest/setuptools.html#automatic-script-creation

It would also be good to be able to run the CLI via the python -m option:

    python -m mqtt_client ....

See https://docs.python.org/3/library/__main__.html

**Comment by sdeancos** [comment]
Thank you for your advice @jamesmyatt  :)
